import { Inter } from 'next/font/google';
import './globals.css';
import MyLink from '../components/MyLink';
import { Box } from '@mui/joy';
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Test Next',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, auth }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box p={2}>
          <Layout name='App'>
            <Box display='flex' gap={2}>
              <MyLink href='/'>home</MyLink>
              <MyLink href='/test-slot'>test-slot</MyLink>
              <MyLink href='/login'>login</MyLink>
            </Box>
            {children}
            {auth}
          </Layout>
        </Box>
      </body>
    </html>
  );
}
