import { Inter } from 'next/font/google';
import './globals.css';
import MyLink from './components/MyLink';
import { Box } from '@mui/joy';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Test Next',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box p={1}>
          <Box p={1} pt={0}>
            <MyLink href='/'>Home</MyLink>
          </Box>
          {children}
        </Box>
      </body>
    </html>
  );
}
